fpga-graphics/README.md, fpga-graphics/ice40/Makefile, fpga-graphics/ice40/icebreaker.pcf, fpga-graphics/ice40/icebreaker_vga.pcf, fpga-graphics/ice40/top_beam.sv, fpga-graphics/ice40/top_beam_vga.sv, fpga-graphics/ice40/top_square.sv, fpga-graphics/ice40/top_square_vga.sv, fpga-graphics/xc7/arty.xdc, fpga-graphics/xc7/display_timings_tb.sv, fpga-graphics/xc7/top_beam.sv, fpga-graphics/xc7/top_square.sv
Use vectors for iCE40 DVI & VGA outputs.
Add Makefile for building iCE40 projects.
Use a parameter for screen coordinate width.
Fix comments on iCEBreaker reset button.
=> FPGA Graphics tidy

fpga-ad-astra/ice40/bram.sv, fpga-ad-astra/ice40/top_greet.sv, fpga-ad-astra/ice40/top_hello_en.sv, fpga-ad-astra/ice40/top_hello_jp.sv
All binaries have been testing on iCEBreaker.
=> Fixed module name to match filename.

fpga-ad-astra/README.md, fpga-ad-astra/ice40/Makefile, fpga-graphics/README.md, fpga-graphics/ice40/Makefile, fpga-pong/README.md, fpga-pong/ice40/Makefile
Improvements to the iCE40 Makefile.
=> iCE40 Makefile

framebuffers/xc7/top_david.sv, framebuffers/xc7/top_david_fizzle.sv, framebuffers/xc7/top_david_v1.sv, framebuffers/xc7/top_david_v2.sv, framebuffers/xc7/top_earth.sv
A few small fixes and improved comments.
=> Framebuffer tweaks

fpga-ad-astra/lint.sh, fpga-graphics/lint.sh, fpga-pong/lint.sh, fpga-pong/xc7/top_pong_v1.sv, framebuffers/lint.sh, hardware-sprites/lint.sh, life-on-screen/lint.sh
=> Improve lint shell script.

README.md, lines-and-triangles/README.md
README fixes. No design changes.
=> Line drawing updates

README.md, hello-arty/I/top.sv, hello-arty/J/top.sv, hello-nexys/E/nexys.xdc, hello-nexys/E/top.sv, hello-nexys/F/nexys.xdc, hello-nexys/F/top.sv, hello-nexys/G/nexys.xdc, hello-nexys/G/top.sv, hello-nexys/H/nexys.xdc, hello-nexys/H/top.sv, hello-nexys/I/nexys.xdc, hello-nexys/I/pwm.sv, hello-nexys/I/top.sv
Add designs for Hello Nexys 2 post.
=> Hello Nexys 2

lines-and-triangles/draw_line.sv, lines-and-triangles/draw_triangle.sv, lines-and-triangles/xc7/draw_framebuffer_tb.sv, lines-and-triangles/xc7/draw_line_tb.sv, lines-and-triangles/xc7/draw_triangle_tb.sv, lines-and-triangles/xc7/vivado/draw_framebuffer_tb_behav.wcfg
Always draw a line in the same direction.
Fix output enable so final pixel of line is drawn.
=> A better line

fpga-graphics/README.md, fpga-graphics/xc7/display_timings_480p_tb.sv, fpga-pong/README.md, fpga-pong/display_timings_1080p.sv, fpga-pong/display_timings_480p.sv, fpga-pong/display_timings_720p.sv, fpga-pong/ice40/Makefile, fpga-pong/ice40/icebreaker.pcf, fpga-pong/ice40/top_pong.sv, fpga-pong/ice40/top_pong_v1.sv, fpga-pong/ice40/top_pong_v2.sv, fpga-pong/ice40/top_pong_v3.sv, fpga-pong/ice40/top_pong_v4.sv, fpga-pong/lint.sh, fpga-pong/xc7-hd/nexys_video.xdc, fpga-pong/xc7-hd/top_pong.sv, fpga-pong/xc7-hd/top_pong_v1.sv, fpga-pong/xc7-hd/top_pong_v2.sv, fpga-pong/xc7-hd/top_pong_v3.sv, fpga-pong/xc7-hd/top_pong_v4.sv, fpga-pong/xc7-hd/vivado/create_project.tcl, fpga-pong/xc7/arty.xdc, fpga-pong/xc7/top_pong.sv, fpga-pong/xc7/top_pong_v1.sv, fpga-pong/xc7/top_pong_v2.sv, fpga-pong/xc7/top_pong_v3.sv, fpga-pong/xc7/top_pong_v4.sv, fpga-pong/xc7/vivado/create_project.tcl
Preparing for new signed display timings for later parts of the graphics series. Brings the simple display timings inside the fpga-pong directory. Makes a number of small improvements, including improving READMEs, naming, and comment consistency.
=> Display Timings Update (Pong)

fpga-ad-astra/ice40/top_hello_en.sv, fpga-ad-astra/ice40/top_hello_jp.sv, fpga-ad-astra/xc7/top_greet.sv, fpga-ad-astra/xc7/top_greet_v1.sv, fpga-ad-astra/xc7/top_hello_en.sv, fpga-ad-astra/xc7/top_hello_jp.sv, hardware-sprites/xc7-hd/top_hedgehog.sv, hardware-sprites/xc7-hd/top_hedgehog_v1.sv, hardware-sprites/xc7-hd/top_sprite_v1.sv, hardware-sprites/xc7-hd/top_sprite_v2.sv, hardware-sprites/xc7-hd/top_sprite_v2a.sv
No fixes for iCE40 Ad Astra issues this time. Made a couple of minor tweaks.
=> Minor Tweaks

fpga-graphics/xc7-hd/nexys_video.xdc, fpga-pong/xc7-hd/nexys_video.xdc, fpga-shapes/xc7-hd/nexys_video.xdc, framebuffers/xc7-hd/nexys_video.xdc, framebuffers/xc7-hd/top_david.sv, framebuffers/xc7-hd/top_david_v3.sv, hardware-sprites/xc7-hd/nexys_video.xdc, lines-and-triangles/xc7-hd/nexys_video.xdc, lines-and-triangles/xc7-hd/top_cube.sv, lines-and-triangles/xc7-hd/top_line.sv, lines-and-triangles/xc7-hd/top_triangles.sv
Tested and fixed issues with scaling on HD screens.
=> Framebuffer HD

lib/README.md, lib/maths/README.md, lib/maths/div.sv, lib/maths/div_int.sv, lib/maths/sqrt.sv, lib/maths/sqrt_int.sv, lib/maths/xc7/div_int_tb.sv, lib/maths/xc7/div_tb.sv, lib/maths/xc7/sqrt_int_tb.sv, lib/maths/xc7/sqrt_tb.sv
These designs come from Project F cookbook blog posts.
=> Add division and square root

hello/hello-arty/D/arty.xdc, hello/hello-arty/K/arty.xdc, hello/hello-arty/K/debounce.sv, hello/hello-arty/K/top.sv, hello/hello-arty/L/arty.xdc, hello/hello-arty/L/pwm.sv, hello/hello-arty/L/top.sv, lib/essential/debounce.sv
Adds timer and traffic light simulations for Hello Arty Part 3.
Increases counter time for debounce module in library.
=> Hello Arty Part 3

graphics/2d-shapes/xc7-hd/top_fb_bounce.sv, graphics/2d-shapes/xc7-hd/top_fb_bounce_v1.sv, graphics/2d-shapes/xc7/top_fb_bounce.sv, graphics/hardware-sprites/xc7-hd/top_hedgehog.sv
Small fixes for issues noticed during video capture.
=> XC7 HD Tweaks

graphics/simple-3d/xc7/arty.xdc, graphics/simple-3d/xc7/top_cube.sv, graphics/simple-3d/xc7/vivado/create_project.tcl
=> Flawed rotation now controlled with buttons.

graphics/fpga-graphics/verilator/README.md, graphics/fpga-graphics/verilator/main_beam.cpp, graphics/fpga-graphics/verilator/main_bounce.cpp, graphics/fpga-graphics/verilator/main_square.cpp
This C++ won't win any awards, but it's a little tidier. :)
=> Tidy up old designs for release

lib/README.md, lib/maths/xc7/sqrt_int_tb.sv, lib/maths/xc7/sqrt_tb.sv
Square root test benches use $monitor.
=> Better Square Root Test Bench

README.md, graphics/README.md, graphics/animated-shapes/README.md, lib/graphics/README.md
The animated shapes blog post isn't ready yet.
=> Animation but not yet

graphics/2d-shapes/xc7/top_castle.sv, graphics/animated-shapes/xc7/top_rotate.sv, graphics/animated-shapes/xc7/vivado/create_project.tcl, lib/graphics/draw_triangle_fill.sv, lib/graphics/xc7/draw_triangle_fill_tb.sv, lib/graphics/xc7/vivado/draw_triangle_fill_tb_behav.wcfg
Fixes an issue with rendering filled triangles. Improves filled triangle test bench.
=> Triangle filled fix

graphics/animated-shapes/README.md, graphics/animated-shapes/xc7-hd/nexys_video.xdc, graphics/animated-shapes/xc7-hd/top_rotate.sv, graphics/animated-shapes/xc7-hd/vivado/create_project.tcl, graphics/animated-shapes/xc7/arty.xdc, graphics/animated-shapes/xc7/top_rotate.sv
Add DVI/HDMI animated shape designs for Nexys Video (xc7-hd).
These designs render a 320x180 framebuffer to a 1280x720p60 display.
=> Animated Shapes Demos for Nexys Video

lib/uart/README.md, lib/uart/examples/arty.xdc, lib/uart/examples/top_uart.sv, lib/uart/uart_baud.sv, lib/uart/uart_rx.sv, lib/uart/uart_tx.sv
Adds my simple SystemVerilog UART implementation to the Verilog library,
=> Add simple UART (8N1) to the library.

graphics/2d-shapes/xc7-hd/top_castle.sv, graphics/2d-shapes/xc7-hd/top_circles.sv, graphics/2d-shapes/xc7-hd/top_cube_fill.sv, graphics/2d-shapes/xc7-hd/top_rainbow.sv, graphics/2d-shapes/xc7-hd/top_rectangles.sv, graphics/2d-shapes/xc7-hd/top_rectangles_fill.sv, graphics/2d-shapes/xc7-hd/top_triangles_fill.sv, graphics/2d-shapes/xc7-hd/vivado/create_project.tcl, graphics/animated-shapes/xc7-hd/top_cube_pieces.sv, graphics/animated-shapes/xc7-hd/top_db_bounce.sv, graphics/animated-shapes/xc7-hd/top_rotate.sv, graphics/animated-shapes/xc7-hd/top_sb_bounce.sv, graphics/animated-shapes/xc7-hd/top_teleport.sv, graphics/animated-shapes/xc7-hd/vivado/create_project.tcl, graphics/animated-shapes/xc7/top_sb_bounce.sv, graphics/lines-and-triangles/xc7-hd/top_cube.sv, graphics/lines-and-triangles/xc7-hd/top_latency_check.sv, graphics/lines-and-triangles/xc7-hd/top_line.sv, graphics/lines-and-triangles/xc7-hd/top_triangles.sv
Also improves palette on Nexys Video and a corrects a palette filename for Arty demo.
=> 2D Shapes for Nexys

graphics/animated-shapes/README.md, maths/demo/README.md, maths/demo/func_circle.sv, maths/demo/func_cubed.sv, maths/demo/func_polynomial.sv, maths/demo/func_squared.sv, maths/demo/lint.sh, maths/demo/sim/README.md, maths/demo/sim/main_graphing.cpp, maths/demo/sim/top_graphing.sv, maths/demo/xc7-hd/nexys_video.xdc, maths/demo/xc7-hd/top_graphing.sv, maths/demo/xc7-hd/vivado/create_project.tcl, maths/demo/xc7/arty.xdc, maths/demo/xc7/top_graphing.sv, maths/demo/xc7/vivado/create_project.tcl
Demo to accompany new blog post on multiplication with DSPs.
=> Integer maths demo

lib/README.md, lib/res/fonts/font_empty.mem, lib/res/fonts/font_unifont_8x16.mem, lib/res/fonts/font_unscii_8x16.mem, lib/res/fonts/font_unscii_8x8.mem, lib/res/fonts/unifont-licences/LICENSE.txt, lib/res/fonts/unifont-licences/OFL-1.1.txt, lib/res/fonts/unifont-licences/README.md, lib/uart/examples/arty.xdc
Add a few bitmap fonts as library resources.
=> Lib res fonts

graphics/ad-astra/ice40/top_lfsr.sv, graphics/ad-astra/starfield.sv, graphics/ad-astra/xc7-hd/top_lfsr.sv, graphics/ad-astra/xc7/top_lfsr.sv, graphics/framebuffers/ice40/top_david_v2.sv, graphics/framebuffers/xc7-hd/top_david_v2.sv, graphics/framebuffers/xc7/top_david_v2.sv, lib/maths/lfsr.sv, lib/maths/xc7/lfsr_tb.sv
=> LFSR seed is now a signal.

lib/display/display_1080p.sv, lib/display/display_24x18.sv, lib/display/display_480p.sv, lib/display/display_720p.sv
The 'de' and 'line' signals weren't being reset.
=> We should reset all control signals to zero.

graphics/fpga-graphics/sim/Makefile, graphics/fpga-graphics/sim/README.md, graphics/fpga-graphics/sim/main_beam.cpp, graphics/fpga-graphics/sim/main_bounce.cpp, graphics/fpga-graphics/sim/main_square.cpp, graphics/fpga-graphics/sim/top_beam.sv, graphics/fpga-graphics/sim/top_bounce.sv, graphics/fpga-graphics/sim/top_square.sv, graphics/pong/sim/Makefile, graphics/pong/sim/README.md, graphics/pong/sim/main_pong.cpp, graphics/pong/sim/top_pong.sv
We need to delay coordinates and date enable one cycle for correct positioning.
I've also added a simple makefile for building simulations.
=> Update Verilator sims to handle SDL offset correctly.

graphics/fpga-graphics/README.md, graphics/fpga-graphics/sim/Makefile, graphics/fpga-graphics/sim/README.md, graphics/racing-the-beam/README.md, graphics/racing-the-beam/sim/Makefile, graphics/racing-the-beam/sim/README.md, lib/display/xc7/display_720p_tb.sv, lib/memory/bram_sdp.sv
Collection of small improvements.
=> Spring 2022 Minor Improvements

graphics/animated-shapes/res/palette/16_colr_4bit_palette.mem, graphics/animated-shapes/res/palette/teleport_16_colr_4bit_palette.mem, lib/display/display_1080p.sv, lib/display/display_24x18.sv, lib/display/display_480p.sv, lib/display/display_720p.sv, lib/res/palettes/antiquity16_4b.mem, lib/res/palettes/fading16_4b.mem, lib/res/palettes/greyscale16_4b.mem, lib/res/palettes/pico8_4b.mem, lib/res/palettes/sepia16_4b.mem, lib/res/palettes/sweetie16_4b.mem, lib/res/palettes/teleport16_4b.mem
* Add reset for display sync signals
* Add seven 4-bit per channel palettes to lib
=> Reset Display Sync & Add Palettes to Lib

graphics/framebuffers/xc7-hd/vivado/create_project.tcl, graphics/framebuffers/xc7/vivado/create_project.tcl, lib/display/linebuffer_simple.sv, lib/display/xc7/linebuffer_simple_tb.sv, lib/display/xc7/vivado/linebuffer_simple_tb_behav.wcfg
A new simple linebuffer design with Vivado test bench.
=> Add Simple Linebuffer

demos/life-on-screen/xc7/top_life.sv, demos/life-on-screen/xc7/vivado/create_project.tcl
Life is the penultimate project to use the old xd module. Only animated shapes remains to be updated (WIP).
=> Switch Life demo to xd2

README.md, demos/ad-astra/README.md, demos/castle-drawing/README.md, demos/life-on-screen/README.md, demos/sinescroll/README.md, demos/sinescroll/render_sinescroll.sv, demos/sinescroll/res/text/greet.mem, demos/sinescroll/sim/Makefile, demos/sinescroll/sim/main_sinescroll.cpp, demos/sinescroll/sim/top_sinescroll.sv, demos/sinescroll/xc7/arty.xdc, demos/sinescroll/xc7/top_sinescroll.sv, demos/sinescroll/xc7/vivado/create_project.tcl
Minor updates for new sine scroll blog post.
=> Sine scroll blog

demos/castle-drawing/sim/top_castle.sv, demos/castle-drawing/xc7/top_castle.sv, demos/castle-drawing/xc7/vivado/create_project.tcl, demos/life-on-screen/lib/display/framebuffer_bram.sv, demos/life-on-screen/lib/display/linebuffer.sv, demos/life-on-screen/xc7/top_life.sv, demos/life-on-screen/xc7/vivado/create_project.tcl, demos/sinescroll/sim/top_sinescroll.sv, demos/sinescroll/xc7/top_sinescroll.sv, demos/sinescroll/xc7/vivado/create_project.tcl
Switch demos over to renamed xd module. Blog has already been updated.
=> Demos xd refactor

lib/maths/README.md, lib/maths/div.sv, lib/maths/divu.sv, lib/maths/mul.sv, lib/maths/test/Makefile, lib/maths/test/mul.gtkw, lib/maths/test/mul.mk, lib/maths/test/mul.py
Simple module that handles fixed-point truncation and Gaussian rounding.
=> Fixed-Point Multiplication Module

demos/mandelbrot/sim/top_mandel.sv, demos/mandelbrot/xc7/top_mandel.sv
Better blanking and button handling.
I've tested in Verilator simulation and on Arty board.
=> Mandelbrot improvements

demos/mandelbrot/verilator-sdl/top_mandel.sv, demos/mandelbrot/xc7-dvi/nexys-video/nexys-video.xdc, demos/mandelbrot/xc7-dvi/top_mandel.sv, demos/mandelbrot/xc7-vga/arty-a7-35/arty-a7-35.xdc, demos/mandelbrot/xc7-vga/top_mandel.sv
Minor improvements to the Mandelbrot files. Designs are unchanged.
=> Minor Mandelbrot Improvements

graphics/hardware-sprites/xc7-hd/top_hedgehog.sv, graphics/hardware-sprites/xc7-hd/top_hourglass.sv, graphics/pong/README.md, graphics/pong/ice40/top_pong.sv, graphics/pong/simple_score.sv, graphics/pong/xc7-hd/nexys_video.xdc, graphics/pong/xc7-hd/top_pong.sv, graphics/pong/xc7-hd/vivado/create_project.tcl, graphics/pong/xc7/top_pong.sv, graphics/racing-the-beam/xc7-hd/top_bounce.sv, graphics/racing-the-beam/xc7-hd/top_colour_cycle.sv, graphics/racing-the-beam/xc7-hd/top_hello.sv, graphics/racing-the-beam/xc7-hd/top_hitomezashi.sv, graphics/racing-the-beam/xc7-hd/top_rasterbars.sv, graphics/racing-the-beam/xc7-hd/vivado/create_project.tcl
Add Pong for Nexys Video and make several small improvements:
* xc7-hd hedgehog and hourglass designs use params for colour widths
* Make simple_score params explicit in top modules
* Put declaration of `pix_addr` before first use in 'simple_score.sv'
* Remove unused 'clock_tb.sv' sim module from Arty Pong 
* Remove superfluous whitespace
=> Add Pong for Nexys Video

lib/display/tmds_encoder_dvi.sv
One of my oldest FPGA modules gets a little love. Testing on Nexys Video.
=> Cleaned up TMDS encoder

graphics/racing-the-beam/ice40/top_hitomezashi.sv, graphics/racing-the-beam/sim/top_hitomezashi.sv, graphics/racing-the-beam/xc7-dvi/top_hitomezashi.sv, graphics/racing-the-beam/xc7/top_hitomezashi.sv
Simple fix for the missing pixel. Thanks to Serg Ko (@vfr1200f). 
Successfully tested in Verilator/SDL simulation and on Nexys Video board.
=> Hitomezashi missing pixel fix (#172)

.gitignore, graphics/fpga-graphics/README.md, graphics/fpga-graphics/ecp5/Makefile, graphics/fpga-graphics/ecp5/top_colour.sv, graphics/fpga-graphics/ecp5/top_flag_ethiopia.sv, graphics/fpga-graphics/ecp5/top_flag_sweden.sv, graphics/fpga-graphics/ecp5/top_square.sv, graphics/fpga-graphics/ecp5/ulx3s.lpf, graphics/fpga-graphics/ice40/Makefile, lib/clock/ecp5/clock_480p.sv, lib/clock/ecp5/clock_720p.sv, lib/clock/ice40/clock_480p.sv, lib/clock/xc7/clock_1080p.sv, lib/clock/xc7/clock_480p.sv, lib/clock/xc7/clock_720p.sv, lib/clock/xc7/clock_sys.sv, lib/display/ecp5/dvi_generator.sv, lib/display/tmds_encoder_dvi.sv
Initial port of _FPGA Graphics_ to ULX3S. 
1280x720p60 display with 74 MHz pixel clock (should be 74.25 MHz, but 74 MHz is within spec that allows for ±0.5%).
Reset button does nothing at the moment: I probably need to read up on the PLL some more.
=> ULX3S FPGA Graphics

README.md
* Note ECP5 support (WIP) - currently covers some designs in _FPGA Graphics_
* Update special sponsor thanks 🙏
* General introduction update
=> June 2024 Update

README.md, graphics/README.md, graphics/fpga-graphics/README.md, graphics/fpga-graphics/sim/README.md
Improve ULX3S support and add Windows to Verilator.
=> FPGA Graphics ULX3S

graphics/fpga-graphics/README.md, graphics/fpga-graphics/sim/README.md, graphics/racing-the-beam/README.md, graphics/racing-the-beam/ecp5/Makefile, graphics/racing-the-beam/ecp5/top_bounce.sv, graphics/racing-the-beam/ecp5/top_colour_cycle.sv, graphics/racing-the-beam/ecp5/top_hello.sv, graphics/racing-the-beam/ecp5/top_hitomezashi.sv, graphics/racing-the-beam/ecp5/top_rasterbars.sv, graphics/racing-the-beam/ecp5/ulx3s.lpf, graphics/racing-the-beam/ice40/top_rasterbars.sv, graphics/racing-the-beam/sim/README.md
Add ULX3S (ECP5) support for _Racing the Beam_ designs. Also include resolution and demo project names.
=> ULX3S Racing the Beam
